In [1]:
import pandas as pd
import csv
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from scipy.stats import pearsonr, spearmanr
from disease import Disease
import networkx as nx

In [2]:
filename = 'data/final_enr.csv'
columns = ['diseaseId', '#snp', '#border_snp', 'pval_tad', 'pval_border', 'pval_outside', 'is_cancer', 'window_size', 'filter']
df = pd.read_csv(filename, usecols=columns)
print(df.head)

FileNotFoundError: [Errno 2] No such file or directory: 'data/final_enr.csv'

In [3]:
df = df[(df['#snp'] != 1) & (df['#border_snp'] != 1)]
df.shape

(52196, 9)

In [4]:
df = df[df['#border_snp'] != 0]
df.shape

(43950, 9)

In [5]:
df_cancers = pd.read_csv("data/cancerous_clustering.csv", usecols=['efoID', 'z_score', 'pvalue', 'p_empirical', 'name'])
df_cancers = df_cancers.rename(columns={'efoID': 'diseaseId'})
df_cancers.shape

(32, 5)

In [6]:
df_noncancers = pd.read_csv("data/noncancerous_clustering.csv", usecols=['efoID', 'z_score', 'pvalue', 'p_empirical', 'name'])
df_noncancers = df_noncancers.rename(columns={'efoID': 'diseaseId'})
df_noncancers.shape

(247, 5)

In [7]:
combined = pd.concat([df_cancers, df_noncancers])

In [8]:
combined.head()

                      name      diseaseId    z_score    pvalue  p_empirical
0     basal cell carcinoma    EFO_0004193   4.690213  0.000031     0.001998
1  squamous cell carcinoma    EFO_0000707   3.968751  0.001300     0.009990
2   keratinocyte carcinoma    EFO_0010176   5.038859  0.004000     0.001998
3       cutaneous melanoma    EFO_0000389  15.667010  0.000000     0.000999
4        colorectal cancer  MONDO_0005575   0.216129  0.002900     0.401598

In [9]:
combined.shape

(279, 5)

In [10]:
def map_genes(row):
    try:
        d = Disease(row['name'], row['diseaseId'])
        genes = d.get_genes()
        return ",".join(genes) if genes else ""
    except Exception as e:
        print(f"Problem with {row['diseaseId']}: {e}")
        return ""


combined['mapped-genes'] = combined.apply(map_genes, axis=1)
combined.to_csv('data/combined_diseases_genes.csv', sep='\t', index=False)

KeyboardInterrupt:

In [3]:
mapped_genes = pd.read_csv('data/combined_diseases_genes.csv', delimiter='\t')

In [4]:
mapped_genes.head()

,name,diseaseId,z_score,pvalue,p_empirical,mapped-genes
0,basal cell carcinoma,EFO_0004193,4.690213,0.000031,0.001998,"TMCC3,KRT19P2,GRXCR1,LINC02383,CSMD1,DTNBP1,AR..."
1,squamous cell carcinoma,EFO_0000707,3.968751,0.001300,0.009990,"SLC45A2,ANKRD11,RPS18P8,RPP40,MICA,LINC01149,L..."
2,keratinocyte carcinoma,EFO_0010176,5.038859,0.004000,0.001998,"RAET1L,RAET1M,PIK3R1,LINC02198,TRPS1,DHX35,LIN..."
3,cutaneous melanoma,EFO_0000389,15.667010,0.000000,0.000999,"RNA5SP293,RPS15AP27,TYR,GPRC5A,MTAP,FMN1,FTO,R..."
4,colorectal cancer,MONDO_0005575,0.216129,0.002900,0.401598,"TERT,MIR4457,RNU1,150P,TTC33,LAMC1,LINC01705,T..."

In [5]:
import networkx as nx
import pandas as pd
from tqdm import tqdm

df = pd.read_csv("data/whole_network.txt", delim_whitespace=True)

G = nx.Graph()
for idx, row in tqdm(df.iterrows(), total=len(df)):
    G.add_edge(row["protein1"], row["protein2"], combined_score=row["combined_score"])

print(f"Nodes: {G.number_of_nodes()}, Edges: {G.number_of_edges()}")

for u, v, d in tqdm(G.edges(data=True), total=G.number_of_edges()):
    d["inv_weight"] = 1 / d["combined_score"]

centrality = nx.betweenness_centrality(G, weight="inv_weight", k=500, seed=42)

print("Done!")
print(centrality)

/var/folders/4g/n465f8j14bq_nt2x3wjkt8pw0000gn/T/ipykernel_76551/1189350060.py:5: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv("data/whole_network.txt", delim_whitespace=True)
100%|██████████| 13715404/13715404 [06:28<00:00, 35273.89it/s]

Nodes: 19622, Edges: 6857702

100%|██████████| 6857702/6857702 [00:04<00:00, 1558475.79it/s]

KeyboardInterrupt:

In [ ]:
print(G.number_of_nodes())
print(G.number_of_edges())

0
0

In [ ]:
aliases_df = pd.read_csv('data/9606.protein.aliases.v12.0.txt', sep='\t')

In [6]:
aliases_df

,string_protein_id,alias,source
0,9606.ENSP00000000233,2B6H,Ensembl_PDB
1,9606.ENSP00000000233,2B6H,UniProt_DR_PDB
2,9606.ENSP00000000233,381,Ensembl_HGNC_entrez_id
3,9606.ENSP00000000233,381,KEGG_GENEID
4,9606.ENSP00000000233,381,KEGG_KEGGID_SHORT
...,...,...,...
3889202,9606.ENSP00000501317,regulatory factor X domain containing 2,Ensembl_HGNC_prev_name
3889203,9606.ENSP00000501317,"regulatory factor X, 7",Ensembl_HGNC_prev_name
3889204,9606.ENSP00000501317,regulatory factor X7,Ensembl_HGNC_name
3889205,9606.ENSP00000501317,uc059jng.1,Ensembl_HGNC_ucsc_id
3889206,9606.ENSP00000501317,uc059jng.1,UniProt_DR_UCSC

In [7]:
centrality

{'9606.ENSP00000000233': 2.0796166872945687e-05,
 '9606.ENSP00000356607': 2.4466078674053748e-05,
 '9606.ENSP00000427567': 9.174779502770155e-07,
 '9606.ENSP00000253413': 5.1276823221037645e-05,
 '9606.ENSP00000493357': 8.787399923764305e-05,
 '9606.ENSP00000324127': 2.2427238784549267e-06,
 '9606.ENSP00000325266': 1.6922371082887175e-05,
 '9606.ENSP00000320935': 0.0003945155186191167,
 '9606.ENSP00000371175': 7.360212001111169e-05,
 '9606.ENSP00000480364': 6.25923846077875e-05,
 '9606.ENSP00000388107': 0.006837657337431171,
 '9606.ENSP00000461784': 8.98108971326723e-05,
 '9606.ENSP00000381097': 2.1305876845321805e-05,
 '9606.ENSP00000234160': 3.996126183428779e-05,
 '9606.ENSP00000241502': 9.684489475146274e-06,
 '9606.ENSP00000317272': 0.0003005249997129602,
 '9606.ENSP00000487719': 5.097099723761198e-06,
 '9606.ENSP00000354878': 1.1009735403324187e-05,
 '9606.ENSP00000479606': 0.0010947041076721923,
 '9606.ENSP00000369127': 4.424282560224719e-05,
 '9606.ENSP00000493946': 0.00034752025916603844,
 '9606.ENSP00000383023': 4.587389751385077e-06,
 '9606.ENSP00000266126': 8.784001857281797e-06,
 '9606.ENSP00000262027': 0.0001264080731492777,
 '9606.ENSP00000271526': 8.206330555255528e-05,
 '9606.ENSP00000364898': 0.0007536571651553306,
 '9606.ENSP00000325074': 0.0006215403403154404,
 '9606.ENSP00000310226': 0.00014842754395592606,
 '9606.ENSP00000006275': 3.353891618234868e-05,
 '9606.ENSP00000369965': 6.534481845861855e-05,
 '9606.ENSP00000258098': 3.639329202765495e-05,
 '9606.ENSP00000265462': 5.280595313816601e-05,
 '9606.ENSP00000347464': 9.990315458571948e-06,
 '9606.ENSP00000330842': 2.5077730640905092e-05,
 '9606.ENSP00000358723': 0.00034537947728205875,
 '9606.ENSP00000363232': 1.5291299171283593e-06,
 '9606.ENSP00000498386': 0.0,
 '9606.ENSP00000225655': 0.0002703501693482939,
 '9606.ENSP00000351926': 0.00020327233698359655,
 '9606.ENSP00000447300': 0.0005087924944258427,
 '9606.ENSP00000264335': 0.0011495998716971004,
 '9606.ENSP00000482829': 2.038839889504479e-07,
 '9606.ENSP00000387549': 1.1825271359125978e-05,
 '9606.ENSP00000386857': 3.486416211052659e-05,
 '9606.ENSP00000271889': 3.313114820444778e-05,
 '9606.ENSP00000377769': 0.00020204903304989387,
 '9606.ENSP00000489407': 0.00020439369892282403,
 '9606.ENSP00000341885': 0.0005488556982546057,
 '9606.ENSP00000307939': 0.00016249553919350698,
 '9606.ENSP00000297532': 1.3456343270729561e-05,
 '9606.ENSP00000222803': 2.6912686541459122e-05,
 '9606.ENSP00000347055': 1.44757632154818e-05,
 '9606.ENSP00000378402': 0.0007713186156981632,
 '9606.ENSP00000258301': 0.00037392323573512144,
 '9606.ENSP00000232905': 1.3456343270729561e-05,
 '9606.ENSP00000323879': 4.4854477569098534e-06,
 '9606.ENSP00000254900': 1.9980630917143896e-05,
 '9606.ENSP00000253055': 1.9470920944767774e-05,
 '9606.ENSP00000466134': 0.0001422090822929374,
 '9606.ENSP00000338864': 1.2538865320452546e-05,
 '9606.ENSP00000311449': 0.0004034864141329364,
 '9606.ENSP00000280706': 3.916271621089853e-05,
 '9606.ENSP00000262455': 3.527193008842749e-05,
 '9606.ENSP00000345133': 7.135939613265677e-07,
 '9606.ENSP00000382250': 0.0015798970303770208,
 '9606.ENSP00000257770': 0.0013339109977083053,
 '9606.ENSP00000351446': 0.0010792089245119584,
 '9606.ENSP00000255006': 2.17136448232227e-05,
 '9606.ENSP00000386248': 1.9572862939243e-05,
 '9606.ENSP00000381601': 0.00014271879226531353,
 '9606.ENSP00000211998': 0.0009053468529344638,
 '9606.ENSP00000253861': 0.00011611193170728008,
 '9606.ENSP00000373684': 5.1276823221037645e-05,
 '9606.ENSP00000305260': 0.00017139507531119404,
 '9606.ENSP00000216373': 1.5699067149184487e-05,
 '9606.ENSP00000157812': 7.778271792089856e-05,
 '9606.ENSP00000219479': 4.8728273359157045e-05,
 '9606.ENSP00000262584': 0.0002329374573758867,
 '9606.ENSP00000248901': 2.9359294408864497e-05,
 '9606.ENSP00000361177': 1.3099546290066278e-05,
 '9606.ENSP00000243440': 1.080585141437374e-05,
 '9606.ENSP00000405926': 0.00014827463096421325,
 '9606.ENSP00000481780': 4.9849635298384513e-05,
 '9606.ENSP00000419195': 9.174779502770155e-07,
 '9606.ENSP00000279387': 0.0003221367025417077,
 '9606.ENSP00000304604': 4.709720144755346e-05,
 '9606.ENSP00000158762': 2.4873846651954644e-05,
 '9606.ENSP00000302968': 9.608032979289857e-05,
 '9606.ENSP00000291906': 3.0582598342567185e-06,
 '9606.ENSP00000249647': 0.00028711962743946823,
 '9606.ENSP00000253686': 5.759722687850153e-05,
 '9606.ENSP00000347140': 1.264080731492777e-05,
 '9606.ENSP00000320866': 0.000996890763973215,
 '9606.ENSP00000429374': 0.0002890055543372599,
 '9606.ENSP00000346173': 5.515061901109616e-05,
 '9606.ENSP00000367220': 0.00014827463096421325,
 '9606.ENSP00000265753': 0.00016657321897251592,
 '9606.ENSP00000369080': 1.3048575292828666e-05,
 '9606.ENSP00000286827': 0.00011060706400561798,
 '9606.ENSP00000357838': 0.00021897140413278105,
 '9606.ENSP00000364298': 2.8441816458587483e-05,
 '9606.ENSP00000363524': 5.0461287265235854e-05,
 '9606.ENSP00000463842': 4.617972349727645e-05,
 '9606.ENSP00000413697': 4.393699961882152e-05,
 '9606.ENSP00000402515': 0.0001431605409080395,
 '9606.ENSP00000359300': 0.0004006320382876301,
 '9606.ENSP00000300087': 0.00010031092256362037,
 '9606.ENSP00000389103': 0.0011003743074894975,
 '9606.ENSP00000401564': 0.00016320913315483356,
 '9606.ENSP00000428714': 3.455833612710092e-05,
 '9606.ENSP00000385432': 3.975737784533734e-05,
 '9606.ENSP00000463559': 6.677200638127168e-05,
 '9606.ENSP00000300651': 0.004379897258549241,
 '9606.ENSP00000286719': 1.0907793408848963e-05,
 '9606.ENSP00000430344': 0.00011692746766308187,
 '9606.ENSP00000359424': 0.00026229675178475123,
 '9606.ENSP00000386264': 5.9432182779055566e-05,
 '9606.ENSP00000269051': 3.058259834256719e-07,
 '9606.ENSP00000357178': 1.0194199447522396e-05,
 '9606.ENSP00000358696': 0.00019634028135928134,
 '9606.ENSP00000219204': 7.2378816077409e-06,
 '9606.ENSP00000381876': 1.5393241165758817e-05,
 '9606.ENSP00000439020': 0.0015237397341704819,
 '9606.ENSP00000397441': 0.0002278403576521255,
 '9606.ENSP00000360613': 3.720882798345674e-05,
 '9606.ENSP00000401888': 0.001395585904365816,
 '9606.ENSP00000239690': 0.0009063662728792161,
 '9606.ENSP00000354451': 2.133985751014688e-05,
 '9606.ENSP00000237264': 4.34272896464454e-05,
 '9606.ENSP00000462468': 4.393699961882152e-05,
 '9606.ENSP00000369784': 7.981208650789407e-06,
 '9606.ENSP00000357048': 7.248075807188423e-05,
 '9606.ENSP00000331748': 4.179621773484182e-06,
 '9606.ENSP00000338844': 0.00011682552566860665,
 '9606.ENSP00000317469': 0.00017054895675704967,
 '9606.ENSP00000262942': 3.4592316791925995e-05,
 '9606.ENSP00000240874': 0.000125184769215575,
 '9606.ENSP00000298552': 0.00022039859205543418,
 '9606.ENSP00000362566': 1.600489313261016e-05,
 '9606.ENSP00000369810': 0.00015016055786200487,
 '9606.ENSP00000362730': 0.00013140323087856368,
 '9606.ENSP00000392718': 9.480605486195827e-06,
 '9606.ENSP00000413152': 1.4271879226531353e-06,
 '9606.ENSP00000303178': 2.1917528812173148e-06,
 '9606.ENSP00000236192': 6.972832422105318e-05,
 '9606.ENSP00000434103': 4.281563767959406e-06,
 '9606.ENSP00000339063': 0.0007856669514205509,
 '9606.ENSP00000354947': 0.0009007594631830788,
 '9606.ENSP00000370719': 0.0009803761608682287,
 '9606.ENSP00000384675': 0.00021051021859133746,
 '9606.ENSP00000349168': 0.000196646107342707,
 '9606.ENSP00000378721': 0.00018318976407197742,
 '9606.ENSP00000382697': 0.00022549569177919538,
 '9606.ENSP00000347134': 9.174779502770155e-07,
 '9606.ENSP00000384700': 2.5179672635380314e-05,
 '9606.ENSP00000258739': 7.441765596691348e-06,
 '9606.ENSP00000261842': 0.00012766535774780545,
 '9606.ENSP00000295408': 8.563127535918812e-05,
 '9606.ENSP00000363779': 5.443702504976959e-05,
 '9606.ENSP00000479134': 6.9320556243152284e-06,
 '9606.ENSP00000300055': 0.00012243233536474396,
 '9606.ENSP00000262305': 4.393699961882152e-05,
 '9606.ENSP00000365012': 9.939344461334335e-05,
 '9606.ENSP00000312778': 4.414088360777197e-05,
 '9606.ENSP00000472985': 7.4876394942052e-05,
 '9606.ENSP00000389277': 0.0006150160526690261,
 '9606.ENSP00000298229': 6.707783236469736e-05,
 '9606.ENSP00000481721': 2.7320454519360018e-05,
 '9606.ENSP00000259056': 2.548549861880599e-06,
 '9606.ENSP00000259808': 0.00042035781421858595,
 '9606.ENSP00000263847': 3.720882798345674e-05,
 '9606.ENSP00000178640': 5.657780693374929e-05,
 '9606.ENSP00000299138': 0.0007282736085309999,
 '9606.ENSP00000256404': 8.29807835028323e-05,
 '9606.ENSP00000300935': 0.0014573627530178016,
 '9606.ENSP00000301037': 5.097099723761198e-06,
 '9606.ENSP00000374484': 4.89321573481075e-06,
 '9606.ENSP00000392513': 8.155359558017916e-07,
 '9606.ENSP00000220003': 7.339823602216124e-05,
 '9606.ENSP00000378769': 0.0006592418879388608,
 '9606.ENSP00000263354': 0.0001685610878647828,
 '9606.ENSP00000380334': 8.038126264371408e-05,
 '9606.ENSP00000361635': 6.269432660226272e-05,
 '9606.ENSP00000273130': 0.000183903358033304,
 '9606.ENSP00000367197': 4.903409934258272e-05,
 '9606.ENSP00000355689': 0.00013741780855260188,
 '9606.ENSP00000257904': 0.0003946344509460045,
 '9606.ENSP00000302886': 0.0006150160526690261,
 '9606.ENSP00000478887': 0.004168612038080857,
 '9606.ENSP00000348461': 0.0004764768821771967,
 '9606.ENSP00000272322': 0.00015434017963548906,
 '9606.ENSP00000417378': 0.00021734033222117746,
 '9606.ENSP00000358997': 0.00025979917292010826,
 '9606.ENSP00000313420': 0.002652207879929489,
 '9606.ENSP00000311430': 0.0003408940295251489,
 '9606.ENSP00000387307': 0.0,
 '9606.ENSP00000263657': 2.8441816458587483e-05,
 '9606.ENSP00000380869': 2.8339874464112257e-05,
 '9606.ENSP00000329419': 0.00016025281531505204,
 '9606.ENSP00000372023': 0.00025516081217148554,
 '9606.ENSP00000360108': 7.849533574592244e-05,
 '9606.ENSP00000341071': 2.8543758453062707e-06,
 '9606.ENSP00000383996': 4.628166549175167e-05,
 '9606.ENSP00000361206': 0.0001391508224586807,
 '9606.ENSP00000411471': 4.38350576243463e-05,
 '9606.ENSP00000432660': 0.00026759773549746285,
 '9606.ENSP00000375220': 5.810693685087765e-06,
 '9606.ENSP00000361298': 7.411182998348782e-05,
 '9606.ENSP00000377148': 0.00020799564939428194,
 '9606.ENSP00000332791': 8.053417563542692e-06,
 '9606.ENSP00000267257': 0.00027779193494498525,
 '9606.ENSP00000346037': 7.176716411055766e-05,
 '9606.ENSP00000378557': 3.0786482331517635e-05,
 '9606.ENSP00000260746': 0.0003496610410500181,
 '9606.ENSP00000264065': 0.0001132575558619738,
 '9606.ENSP00000438388': 5.586421297242272e-05,
 '9606.ENSP00000357283': 0.00036536010819920265,
 '9606.ENSP00000380638': 0.0016966206140511522,
 '9606.ENSP00000329471': 5.056322925971108e-05,
 '9606.ENSP00000313007': 0.0009077934608018693,
 '9606.ENSP00000355428': 2.7524338508310468e-06,
 '9606.ENSP00000371230': 0.00030337937555826645,
 '9606.ENSP00000271857': 1.0194199447522394e-06,
 '9606.ENSP00000376345': 0.005296702148943686,
 '9606.ENSP00000270142': 0.0015409551884874853,
 '9606.ENSP00000353846': 3.527193008842749e-05,
 '9606.ENSP00000381098': 0.00020785972673498164,
 '9606.ENSP00000364555': 2.997094637571584e-05,
 '9606.ENSP00000337261': 7.53351339171905e-05,
 '9606.ENSP00000364579': 3.669911801108062e-06,
 '9606.ENSP00000303507': 0.00017493246251948429,
 '9606.ENSP00000342136': 0.00012029155348076426,
 '9606.ENSP00000411831': 1.6310719116035832e-06,
 '9606.ENSP00000378323': 0.0006198922780714243,
 '9606.ENSP00000275364': 0.00037934315177472086,
 '9606.ENSP00000494678': 2.0490340889520014e-05,
 '9606.ENSP00000360793': 4.169427574036659e-05,
 '9606.ENSP00000494750': 0.013473418554804162,
 '9606.ENSP00000265709': 0.0004335932831679525,
 '9606.ENSP00000285873': 3.486416211052659e-05,
 '9606.ENSP00000416097': 0.00018971405171839178,
 '9606.ENSP00000423399': 0.0001426168502708383,
 '9606.ENSP00000355651': 7.502930793376482e-05,
 '9606.ENSP00000349016': 7.339823602216124e-06,
 '9606.ENSP00000364449': 1.936897895029255e-06,
 '9606.ENSP00000357810': 5.097099723761197e-07,
 '9606.ENSP00000386786': 1.8553442994490757e-05,
 '9606.ENSP00000479816': 2.997094637571584e-05,
 '9606.ENSP00000424711': 1.2029155348076426e-05,
 '9606.ENSP00000446955': 0.00029094245223228914,
 '9606.ENSP00000309415': 6.626229640889557e-06,
 '9606.ENSP00000356864': 8.583515934813856e-05,
 '9606.ENSP00000262146': 9.990315458571948e-06,
 '9606.ENSP00000298159': 5.311177912159168e-05,
 '9606.ENSP00000221114': 0.00012661195713822816,
 '9606.ENSP00000203556': 4.179621773484182e-06,
 '9606.ENSP00000337797': 1.8757326983441205e-05,
 '9606.ENSP00000354669': 4.719914344202869e-05,
 '9606.ENSP00000347244': 0.0007995310626691814,
 '9606.ENSP00000318821': 0.0002670880255250867,
 '9606.ENSP00000373215': 8.767011524869259e-06,
 '9606.ENSP00000377948': 2.9563178397814946e-06,
 '9606.ENSP00000370208': 0.0002840103966079739,
 '9606.ENSP00000300176': 3.058259834256719e-07,
 '9606.ENSP00000380070': 0.004885570085225108,
 '9606.ENSP00000360532': 0.001040878734589274,
 '9606.ENSP00000046087': 2.059228288399524e-05,
 '9606.ENSP00000380718': 0.00015362658567416248,
 '9606.ENSP00000258955': 0.0008165213950817188,
 '9606.ENSP00000469035': 4.5873897513850775e-05,
 '9606.ENSP00000331901': 0.00029603955195605037,
 '9606.ENSP00000269881': 0.0005940160018071299,
 '9606.ENSP00000244496': 0.00011529639575147829,
 '9606.ENSP00000367658': 1.2436923325977322e-05,
 '9606.ENSP00000293831': 0.000504561901655121,
 '9606.ENSP00000219252': 0.0018244049041258453,
 '9606.ENSP00000258457': 1.0194199447522395e-07,
 '9606.ENSP00000385000': 0.0002154034343261482,
 '9606.ENSP00000219476': 0.0002737142551659763,
 '9606.ENSP00000463939': 4.006320382876301e-05,
 '9606.ENSP00000442736': 5.4335083055294366e-05,
 '9606.ENSP00000331602': 0.00026229675178475123,
 '9606.ENSP00000236709': 3.3640858176823903e-06,
 '9606.ENSP00000218340': 3.567969806632838e-06,
 '9606.ENSP00000299705': 1.238595232873971e-05,
 '9606.ENSP00000223369': 0.0002329374573758867,
 '9606.ENSP00000295240': 1.315051728730389e-05,
 '9606.ENSP00000471457': 2.7320454519360018e-05,
 '9606.ENSP00000357660': 8.25730155249314e-06,
 '9606.ENSP00000310491': 2.5077730640905092e-05,
 '9606.ENSP00000322170': 7.569193089785379e-05,
 '9606.ENSP00000345656': 0.0005477343363153782,
 '9606.ENSP00000239440': 5.708751690612541e-06,
 '9606.ENSP00000387875': 4.587389751385077e-06,
 '9606.ENSP00000273375': 5.097099723761198e-06,
 '9606.ENSP00000302830': 3.9043783884010774e-05,
 '9606.ENSP00000256858': 2.2325296790074044e-05,
 '9606.ENSP00000356000': 4.291757967406928e-05,
 '9606.ENSP00000381339': 0.00019674804933718222,
 '9606.ENSP00000306124': 0.0006492685628127013,
 '9606.ENSP00000285208': 8.767011524869259e-06,
 '9606.ENSP00000363638': 0.00012498088522662457,
 '9606.ENSP00000379287': 0.0010739589117964843,
 '9606.ENSP00000356920': 9.07283750829493e-06,
 '9606.ENSP00000243298': 2.1509760834272253e-05,
 '9606.ENSP00000437073': 4.424282560224719e-05,
 '9606.ENSP00000266037': 1.4373821221006577e-05,
 '9606.ENSP00000416250': 1.4084985569993445e-05,
 '9606.ENSP00000003100': 6.432539851386631e-05,
 '9606.ENSP00000380524': 6.728171635364781e-06,
 '9606.ENSP00000290378': 0.00014649064606089683,
 '9606.ENSP00000361803': 1.936897895029255e-06,
 '9606.ENSP00000365773': 5.372343108844302e-05,
 '9606.ENSP00000362294': 4.587389751385077e-06,
 '9606.ENSP00000480707': 2.0490340889520014e-05,
 '9606.ENSP00000270176': 1.0601967425423291e-05,
 '9606.ENSP00000376367': 0.00021132575454713923,
 '9606.ENSP00000361264': 2.4058310696152853e-05,
 '9606.ENSP00000294618': 2.4058310696152853e-05,
 '9606.ENSP00000370695': 6.656812239232124e-05,
 '9606.ENSP00000423673': 0.0007231510233086199,
 '9606.ENSP00000416750': 1.8553442994490757e-05,
 '9606.ENSP00000371267': 0.00012905856500563352,
 '9606.ENSP00000263125': 0.00013007798495038575,
 '9606.ENSP00000361275': 2.2121412801123596e-05,
 '9606.ENSP00000009530': 0.002437891826877743,
 '9606.ENSP00000369390': 3.975737784533734e-06,
 '9606.ENSP00000366283': 4.281563767959406e-06,
 '9606.ENSP00000300093': 0.005470156452543279,
 '9606.ENSP00000360916': 2.2835006762450165e-05,
 '9606.ENSP00000388169': 9.745654671831409e-05,
 '9606.ENSP00000444561': 3.669911801108062e-06,
 '9606.ENSP00000393541': 3.0276772359141514e-05,
 '9606.ENSP00000296474': 1.6616545099461504e-05,
 '9606.ENSP00000314733': 8.155359558017917e-05,
 '9606.ENSP00000232975': 3.5068046099477036e-05,
 '9606.ENSP00000349305': 6.799531031497438e-05,
 '9606.ENSP00000264995': 0.0005018094678042899,
 '9606.ENSP00000481994': 4.077679779008958e-07,
 '9606.ENSP00000265062': 0.0002784035869118366,
 '9606.ENSP00000262288': 2.446607867405375e-06,
 '9606.ENSP00000265431': 9.70487787404132e-05,
 '9606.ENSP00000255194': 0.00011463377278738934,
 '9606.ENSP00000229812': 9.745654671831409e-05,
 '9606.ENSP00000263904': 6.177684865198571e-05,
 '9606.ENSP00000340454': 0.00032458331040911305,
 '9606.ENSP00000223073': 9.70487787404132e-05,
 '9606.ENSP00000313869': 7.360212001111169e-05,
 '9606.ENSP00000287878': 9.789829536104006e-05,
 '9606.ENSP00000256460': 4.077679779008958e-06,
 '9606.ENSP00000365162': 7.115551214370632e-05,
 '9606.ENSP00000222286': 4.200010172379227e-05,
 '9606.ENSP00000326238': 4.291757967406928e-05,
 '9606.ENSP00000328287': 3.9043783884010774e-05,
 '9606.ENSP00000334300': 7.74759158011702e-06,
 '9606.ENSP00000258886': 0.00024364136679578524,
 '9606.ENSP00000446830': 4.077679779008958e-07,
 '9606.ENSP00000428489': 0.00010265558843655052,
 '9606.ENSP00000378338': 0.00011305367187302337,
 '9606.ENSP00000456206': 3.099036632046808e-05,
 '9606.ENSP00000254976': 0.001870431714631409,
 '9606.ENSP00000262177': 1.9470920944767774e-05,
 '9606.ENSP00000367806': 0.0002542178487225897,
 '9606.ENSP00000368237': 3.2621438232071664e-06,
 '9606.ENSP00000360676': 1.6922371082887175e-05,
 '9606.ENSP00000355966': 9.460217087300783e-05,
 '9606.ENSP00000338777': 1.7228197066312848e-05,
 '9606.ENSP00000203407': 0.00017901014229849326,
 '9606.ENSP00000296255': 0.00013617751428648665,
 '9606.ENSP00000386588': 3.924766787296122e-05,
 '9606.ENSP00000430276': 1.7635965044213744e-05,
 '9606.ENSP00000371554': 1.3660227259680009e-05,
 '9606.ENSP00000280772': 0.00028277010234185873,
 '9606.ENSP00000350896': 2.038839889504479e-06,
 '9606.ENSP00000234313': 0.00026836230045602705,
 '9606.ENSP00000203630': 7.135939613265677e-07,
 '9606.ENSP00000326342': 3.87379579005851e-06,
 '9606.ENSP00000216133': 2.9563178397814946e-06,
 '9606.ENSP00000338127': 6.116519668513437e-07,
 '9606.ENSP00000239891': 5.938121178181795e-05,
 '9606.ENSP00000319060': 1.620877712156061e-05,
 '9606.ENSP00000363308': 0.00023008308153058045,
 '9606.ENSP00000009105': 6.116519668513437e-06,
 '9606.ENSP00000364361': 2.0796166872945687e-05,
 '9606.ENSP00000264028': 4.8728273359157045e-05,
 '9606.ENSP00000371133': 3.629135003317972e-05,
 '9606.ENSP00000365891': 0.0007040114138458966,
 '9606.ENSP00000393241': 0.0012247920845561639,
 '9606.ENSP00000331849': 5.515061901109616e-05,
 '9606.ENSP00000346839': 0.006197614525118478,
 '9606.ENSP00000310722': 2.7524338508310468e-06,
 '9606.ENSP00000309714': 5.097099723761198e-06,
 '9606.ENSP00000267814': 0.00036495234022130175,
 '9606.ENSP00000326381': 1.7686936041451357e-05,
 '9606.ENSP00000361917': 3.231561224864599e-05,
 '9606.ENSP00000307078': 0.00032911972916326054,
 '9606.ENSP00000413436': 3.9553493856386896e-05,
 '9606.ENSP00000335153': 0.005673683644513064,
 '9606.ENSP00000358071': 4.34272896464454e-05,
 '9606.ENSP00000263265': 4.138844975694092e-05,
 '9606.ENSP00000389445': 0.00034232121744780204,
 '9606.ENSP00000320295': 0.0001111167739779941,
 '9606.ENSP00000361900': 1.0194199447522395e-07,
 '9606.ENSP00000246069': 1.0194199447522395e-07,
 '9606.ENSP00000436785': 3.0174830364666288e-05,
 '9606.ENSP00000274710': 8.155359558017916e-07,
 '9606.ENSP00000397947': 2.9563178397814944e-05,
 '9606.ENSP00000457728': 0.00014496151614376847,
 '9606.ENSP00000350348': 6.228655862436184e-05,
 '9606.ENSP00000376293': 3.771853795583286e-06,
 '9606.ENSP00000451560': 0.0,
 '9606.ENSP00000409952': 0.00011009735403324186,
 '9606.ENSP00000305071': 7.003415020447885e-05,
 '9606.ENSP00000255136': 5.4538967044244816e-06,
 '9606.ENSP00000385886': 1.1519445375700307e-05,

In [9]:
alias_to_protein = dict(zip(aliases_df['alias'], aliases_df['string_protein_id']))

In [10]:
expanded = mapped_genes.copy()
expanded["mapped-genes"] = expanded["mapped-genes"].str.split(",")
expanded = expanded.explode("mapped-genes")

expanded["protein_id"] = expanded["mapped-genes"].map(alias_to_protein)

expanded["centrality"] = expanded["protein_id"].map(centrality).fillna(0)

mean_centrality = expanded.groupby(expanded.index)["centrality"].mean()

mapped_genes["mean_centrality"] = mean_centrality

In [11]:
mapped_genes

,name,diseaseId,z_score,pvalue,p_empirical,mapped-genes,mean_centrality
0,basal cell carcinoma,EFO_0004193,4.690213,3.120000e-05,0.001998,"TMCC3,KRT19P2,GRXCR1,LINC02383,CSMD1,DTNBP1,AR...",0.000209
1,squamous cell carcinoma,EFO_0000707,3.968751,1.300000e-03,0.009990,"SLC45A2,ANKRD11,RPS18P8,RPP40,MICA,LINC01149,L...",0.000228
2,keratinocyte carcinoma,EFO_0010176,5.038859,4.000000e-03,0.001998,"RAET1L,RAET1M,PIK3R1,LINC02198,TRPS1,DHX35,LIN...",0.000423
3,cutaneous melanoma,EFO_0000389,15.667010,0.000000e+00,0.000999,"RNA5SP293,RPS15AP27,TYR,GPRC5A,MTAP,FMN1,FTO,R...",0.000296
4,colorectal cancer,MONDO_0005575,0.216129,2.900000e-03,0.401598,"TERT,MIR4457,RNU1,150P,TTC33,LAMC1,LINC01705,T...",0.000068
...,...,...,...,...,...,...,...
274,erythematosquamous dermatosis,EFO_1000695,14.059322,2.390000e-11,0.000999,"CARD14,TYR,IL12B,LINC01845,IRF4,ZMIZ1,IL2RA,IL...",0.000051
275,color vision disorder,MONDO_0001703,0.298102,6.790000e-07,0.350649,"AMZ1,NRF1,SFRP4,STARD3NL,ZNF775,RABGEF1,SEMA3D...",0.000056
276,QRS-T angle,EFO_0020097,4.241194,1.200000e-03,0.007992,"HAND1,CIR1P1,HNRNPLP1,RPS26P29,PPP1R3B,DT,KLHL...",0.000083
277,pregnancy disorder,EFO_0009682,1.421844,6.900000e-03,0.117882,"HELZ2,GMEB2,ZSCAN2,AS1,MAST4,TRMU,SLC1A3,PURPL...",0.000055
278,"drug use measurement, chronic lung disease",EFO_0009910,44.811523,2.160000e-07,0.000999,"HTR4,SERPINA1,PSMA4,CHRNA5,CHRNA4,GUSBP5,KRT18...",0.000203

In [13]:
mapped_genes.to_csv("data/mean_centrality_test.csv", sep='\t')